# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "YoungbinLab Blog"
description: "Logs of Youngbin han's Laboratory"
email: sukso96100@gmail.com
name: "Youngbin Han"

url: "http://blog.youngbin.xyz/" # the base hostname & protocol for your site
baseurl: ""

disqus: youngbinhan

google_analytics: UA-46663268-3
adsense_client: ca-pub-7051197638651710
adsense_slot: 3015305584

coinhive: jXepLL4Yglrjb4Lo0aftL9PJzVeA0pba

paginate: 10
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

menu:
  main:
    - title: Home
      path: /
      icon: fas fa-home
    - title: Tags
      path: /tags
      icon: fas fa-tags
    - title: Archive
      path: /archive
      icon: fas fa-archive
  links:
    - title: youngbin.xyz
      url: https://youngbin.xyz
      icon: fas fa-globe
    - title: GitHub
      url: https://github.com/sukso96100
      icon: fab fa-github
    - title: Facebook
      url: https://fb.com/hanyoungbin
      icon: fab fa-facebook
    - title: Twitter
      url: https://twitter.com/sukso96100
      icon: fab fa-twitter
    - title: Google Plus
      url: google.com/+한영빈96
      icon: fab fa-google-plus
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
